module.exports = [
  {
    name: 'Nosso Lar',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1944,
    publisher: 'FEB',
  },
  {
    name: 'Os mensageiros',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1944,
    publisher: 'FEB',
  },
  {
    name: 'Missionários da luz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1945,
    publisher: 'FEB',
  },
  {
    name: 'Obreiros da vida eterna',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1946,
    publisher: 'FEB',
  },
  {
    name: 'No mundo maior',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1947,
    publisher: 'FEB',
  },
  {
    name: 'Libertação',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1949,
    publisher: 'FEB',
  },
  {
    name: 'Entre a Terra e o Céu',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1954,
    publisher: 'FEB',
  },
  {
    name: 'Nos domínios da mediunidade',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1954,
    publisher: 'FEB',
  },
  {
    name: 'Ação e reação',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1957,
    publisher: 'FEB',
  },
  {
    name: 'Evolução em dois mundos',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1958,
    publisher: 'FEB',
  },
  {
    name: 'Mecanismos da mediunidade',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1960,
    publisher: 'FEB',
  },
  {
    name: 'Sexo e destino',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1965,
    publisher: 'FEB',
  },
  {
    name: 'E a vida continua...',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1968,
    publisher: 'FEB',
  },
  {
    name: 'Agenda cristã',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1948,
    publisher: 'FEB',
  },
  {
    name: 'Conduta espírita',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1960,
    publisher: 'FEB',
  },
  {
    name: 'Desobsessão',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1964,
    publisher: 'FEB',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. I',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. II',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. III',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Vivendo a Doutrina Espírita - Vol. IV',
    authors: ['Antônio Baduy Filho'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 2015,
    publisher: 'ide',
  },
  {
    name: 'Opinião Espírita',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1963,
    publisher: 'FEB',
  },
  {
    name: 'Sol nas Almas',
    authors: ['Waldo Vieira'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1964,
    publisher: 'FEB',
  },
  {
    name: 'Estude e Viva',
    authors: ['Francisco Cândido Xavier', 'Waldo Vieira'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1965,
    publisher: 'FEB',
  },
  {
    name: 'Sinal Verde',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1971,
    publisher: 'FEB',
  },
  {
    name: 'Respostas da Vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1975,
    publisher: 'FEB',
  },
  {
    name: 'Busca e Acharás',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1976,
    publisher: 'FEB',
  },
  {
    name: 'Endereços da Paz',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1982,
    publisher: 'FEB',
  },
  {
    name: 'Cidade no Além',
    authors: ['Francisco Cândido Xavier', 'Heigorina Cunha'],
    spiritualAuthors: ['André Luiz', 'Lucius'],
    datePsychography: 1983,
    publisher: 'FEB',
  },
  {
    name: 'Apostilas da Vida',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['André Luiz'],
    datePsychography: 1986,
    publisher: 'FEB',
  },
  {
    name: 'Caminho Espírita',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: [
      'Emmanuel',
      'Albino Teixeira',
      'André Luiz',
      'Meimei',
      'Irmão X',
      'Hilário Silva',
      'Bezerra de Menezes',
      'Albino Silva',
      'Fabiano',
    ],
    datePsychography: 1967,
    publisher: 'FEB',
  },
  {
    name: 'Ação e Caminho',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1987,
    publisher: 'FEB',
  },
  {
    name: 'A Verdade Responde',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1990,
    publisher: 'FEB',
  },
  {
    name: 'Tempo e Nós',
    authors: ['Francisco Cândido Xavier'],
    spiritualAuthors: ['Emmanuel', 'André Luiz'],
    datePsychography: 1993,
    publisher: 'FEB',
  },
];
